name: multipliers
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  youtube_player_flutter: ^6.1.0+4
  refined_markdown: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/9E5 HEALTH DRINK.png
    - assets/images/BELOW 37.png
    - assets/images/BLOOD PURIFIER.png
    - assets/images/COF NIL.png
    - assets/images/DAILY DETOX.png
    - assets/images/DIABA LIFE.png
    - assets/images/FEALING SYRUP.png
    - assets/images/IMMUNO 3 CAP.png
    - assets/images/KAVACH PRASH.png
    - assets/images/LIV a'GAIN CAP.png
    - assets/images/LIV a'GAIN SYRUP.png
    - assets/images/MAN SHAKTIMAN.png
    - assets/images/PHYT STRESS.png
    - assets/images/SPIRULINA GOLD.png
    - assets/images/URI FLUSH-3.png
    - assets/images/WOMAN COMPANION.png
    - assets/images/PROTEIN POWDER.png
    - assets/images/NUTRILIFE.png
    - assets/images/NO VEDNA GEL.png
    - assets/images/NO VEDNA CAP.png
    - assets/images/WELL HART.png
    - assets/images/MAHA BHRINGRAJ OIL.png
    - assets/images/WOUND HEALING CRM.png
    - assets/images/NATCIUM.png
    - assets/images/ThyHealth.png
    - assets/images/MELT FAT.png
    - assets/images/CYCLOVA.png
    - assets/images/ANTILERGY.png
    - assets/images/AYUSHWAAS.png

    - assets/images/En.png
    - assets/images/Hi.png

    - assets/docs/9E5 HEALTH DRINK ENGLISH.md
    - assets/docs/9E5 HEALTH DRINK HINDI.md
    - assets/docs/ANTILERGY ENGLISH.md
    - assets/docs/ANTILERGY HINDI.md
    - assets/docs/AYUSHWAAS ENGLISH.md
    - assets/docs/AYUSHWAAS HINDI.md
    - assets/docs/BELOW 37 ENGLISH.md
    - assets/docs/BELOW 37 HINDI.md
    - assets/docs/BLOOD PURIFIER ENGLISH.md
    - assets/docs/BLOOD PURIFIER HINDI.md
    - assets/docs/COF NIL ENGLISH.md
    - assets/docs/COF NIL HINDI.md
    - assets/docs/CYCLOVA ENGLISH.md
    - assets/docs/CYCLOVA HINDI.md
    - assets/docs/DAILY DETOX ENGLISH.md
    - assets/docs/DAILY DETOX HINDI.md
    - assets/docs/DIABA LIFE ENGLISH.md
    - assets/docs/DIABA LIFE HINDI.md
    - assets/docs/FEALING SYRUP ENGLISH.md
    - assets/docs/FEALING SYRUP HINDI.md
    - assets/docs/IMMUNO 3 CAP ENGLISH.md
    - assets/docs/IMMUNO 3 CAP HINDI.md
    - assets/docs/KAVACH PRASH ENGLISH.md
    - assets/docs/KAVACH PRASH HINDI.md
    - assets/docs/LIV a'GAIN CAP ENGLISH.md
    - assets/docs/LIV a'GAIN CAP HINDI.md
    - assets/docs/LIV a'GAIN SYRUP ENGLISH.md
    - assets/docs/LIV a'GAIN SYRUP HINDI.md
    - assets/docs/MAHA BHRINGRAJ OIL ENGLISH.md
    - assets/docs/MAHA BHRINGRAJ OIL HINDI.md
    - assets/docs/MAN SHAKTIMAN ENGLISH.md
    - assets/docs/MAN SHAKTIMAN HINDI.md
    - assets/docs/MELT FAT ENGLISH.md
    - assets/docs/MELT FAT HINDI.md
    - assets/docs/NATCIUM ENGLISH.md
    - assets/docs/NATCIUM HINDI.md
    - assets/docs/NO VEDNA CAP ENGLISH.md
    - assets/docs/NO VEDNA CAP HINDI.md
    - assets/docs/NO VEDNA GEL ENGLISH.md
    - assets/docs/NO VEDNA GEL HINDI.md
    - assets/docs/NUTRILIFE ENGLISH.md
    - assets/docs/NUTRILIFE HINDI.md
    - assets/docs/PHYT STRESS ENGLISH.md
    - assets/docs/PHYT STRESS HINDI.md
    - assets/docs/PROTEIN POWDER ENGLISH.md
    - assets/docs/PROTEIN POWDER HINDI.md
    - assets/docs/SPIRULINA GOLD ENGLISH.md
    - assets/docs/SPIRULINA GOLD HINDI.md
    - assets/docs/ThyHealth ENGLISH.md
    - assets/docs/ThyHealth HINDI.md
    - assets/docs/URI FLUSH-3 ENGLISH.md
    - assets/docs/URI FLUSH-3 HINDI.md
    - assets/docs/WELL HART ENGLISH.md
    - assets/docs/WELL HART HINDI.md
    - assets/docs/WOMAN COMPANION ENGLISH.md
    - assets/docs/WOMAN COMPANION HINDI.md
    - assets/docs/WOUND HEALING CRM ENGLISH.md
    - assets/docs/WOUND HEALING CRM HINDI.md


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Alatsi
      fonts:
        - asset: assets/Alatsi-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
